### ISSUE TITLE
Product name and domain

### ISSUE THREAD

**Issue by joshoua** [cgraha37/Senior-Design#16]
Comment your ideas for the name of our product, and what our domain could be. The domain doesn't have to match the name of the product exactly, as this would limit what we can name our product. Also make sure if you suggest a domain that it is available to rent!

**Comment by joshoua** [comment]
### Product name: 
- Haven
- NeoNet
- Net Pal

### Domain:
hypertexthaven,com
supermegaawesomewow.com

https://media.discordapp.net/attachments/1162483087905656843/1202369157396570192/image.png?ex=65cd348a&is=65babf8a&hm=8124f0d1649ff8dbbe7c2892cdd157ff250dea41a305ab857db4735ec2fe172a&=&format=webp&quality=lossless

https://media.discordapp.net/attachments/1162483087905656843/1202359722821558272/image.png?ex=65cd2bc0&is=65bab6c0&hm=1fd9972a4c9bcd0b75984872d86ebc7e40d22a927b5a5f3362bcdb8db97546ec&=&format=webp&quality=lossless

**Comment by noahvanfleet** [comment]
### Name + Domain
- relletin (restricted bulletin) | relletin.com ($5.98 on namecheap)
- bulleve (bulletin exclusive) | bulleve.com ($5.98 on namecheap)
- boalder (board holder) | boalder.com ($5.98 on namecheap)
